Repository axb8292/stso-capstone, pull requests merged in 2021-12, with the labels that each got.

#37 Add fish button image
  css/main.css
  img/fish-button.png
  info/what.html
Labels: enhancement

#39 Add final text
  betta/betta-mahachaiensis.html
  betta/betta-splendens.html
Labels: content

#40 Add references page
  css/main.css
  img/Betta_Boi.png
  img/Patriot.png
  img/Starburst.png
  img/Steve.png
  img/Sylvia.png
  info/better.html
  info/references.html
  info/thanks.html
  js/slideshow.js
Labels: enhancement, content

#41 Add final pleco text
  img/homeplecos.jpg
  img/plecoinvasion.jpg
  img/riskplecos.png
  img/toothless.jpg
  pleco/ancistrus-cirrhosus.html
  pleco/hypostomus-plecostomus.html
Labels: content
